import {notFound} from 'next/navigation';
import Image from 'next/image';
import {publicProjects} from '@/lib/projects';
import Capture from '@/components/Capture';
import Back from '@/components/Back';
import PrepayCaseStudy from '@/components/PrepayCaseStudy';
import ProjectCaseStudy from '@/components/ProjectCaseStudy';
import {caseStudies} from '@/lib/case-studies';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=(await publicProjects()).find(p=>p.slug===slug);return {title:p?.title??'기록을 찾을 수 없어요',description:p?.summary,openGraph:{title:p?.title,description:p?.summary}};}
export default async function Detail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const projects=await publicProjects();const p=projects.find(p=>p.slug===slug);if(!p)notFound();if(p.slug==='online-prepay')return <PrepayCaseStudy project={p}/>;if(caseStudies[p.slug])return <ProjectCaseStudy project={p} study={caseStudies[p.slug]} nextProject={projects[(projects.indexOf(p)+1)%projects.length]}/>;return <main id="main" className="shell detail"><Back slug={p.slug}/><div className="detail-heading"><div className="eyebrow">{p.category}</div><h1>{p.title}</h1><p>{p.summary}</p><div className="status">● {p.status}</div></div><Image className="cover" src={p.coverSrc} alt={`${p.title} 디자인 커버`} width={1200} height={720} priority/>{p.screenshotSrcs.map((src,i)=><Capture key={i} src={src} title={p.title} note={p.capture_note} url={p.url}/>)}<p className="capture-date">화면 확인: {p.captured_at?new Date(p.captured_at).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'}):'확인 시점 미기록'}</p><div className="story"><section><span>01 / WHY</span><div><h2>왜 만들었나요?</h2><p>{p.problem}</p></div></section><section><span>02 / HOW TO USE</span><div><h2>이렇게 사용해요</h2><ol>{p.steps.split('\n').filter(Boolean).map((s,i)=><li key={i}>{s}</li>)}</ol></div></section><section><span>03 / MAKING</span><div><h2>어떻게 만들었나요?</h2><p>{p.process}</p></div></section><section><span>04 / CURRENT</span><div><h2>지금 가능한 것</h2><p>{p.scope}</p></div></section>{p.next&&<section><span>05 / NEXT</span><div><h2>다음에 고칠 점</h2><p>{p.next}</p></div></section>}</div><div className="detail-actions"><Back slug={p.slug}/><a className="primary" href={p.url} target="_blank" rel="noopener noreferrer">실제 사이트 보기 ↗</a></div></main>;}
