"use client";
import {createClient,type SupabaseClient} from '@supabase/supabase-js';
import Image from 'next/image';
import {useCallback,useEffect,useRef,useState} from 'react';
import {projectSchema,type Project,type ViewProject} from '@/lib/schema';
const names={draft:'임시저장',published:'공개',hidden:'비공개',trash:'휴지통'};
function empty():ViewProject{return {id:crypto.randomUUID(),slug:'project-'+crypto.randomUUID().slice(0,8),title:'',summary:'',url:'',category:'',status:'',cover:'',screenshots:[],capture_note:'실제 사이트 화면 · 대표 구간',captured_at:'',problem:'',steps:'',process:'',scope:'',next:'',visibility:'draft',sort_order:60,updated_at:null,coverSrc:'',screenshotSrcs:[]};}
export default function Admin({ready}:{ready:boolean}){
 const db=useRef<SupabaseClient|null>(null);const [signedIn,setSignedIn]=useState(false);const [allowed,setAllowed]=useState(false);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(ready);const [message,setMessage]=useState('');const [rows,setRows]=useState<ViewProject[]>([]);const [edit,setEdit]=useState<ViewProject|null>(null);const [dirty,setDirty]=useState(false);const [preview,setPreview]=useState(false);const [filter,setFilter]=useState('active');
 const request=useCallback(async(path:string,options:RequestInit={})=>{if(!db.current)throw new Error('로그인 연결을 확인해 주세요.');const {data:{session}}=await db.current.auth.getSession();if(!session)throw new Error('다시 로그인해 주세요.');const headers=new Headers(options.headers);headers.set('Authorization',`Bearer ${session.access_token}`);const res=await fetch(path,{...options,headers,cache:'no-store'});if(!res.ok){const body=await res.json().catch(()=>({error:'요청을 처리하지 못했습니다.'}));throw new Error(body.error);}return res;},[]);
 const refresh=useCallback(async()=>{setLoading(true);try{const res=await request('/api/admin/projects');setRows(await res.json());setAllowed(true);}catch(e){setMessage(e instanceof Error?e.message:'목록 확인에 실패했습니다.');setAllowed(false);}finally{setLoading(false);}},[request]);
 useEffect(()=>{if(!ready)return;db.current=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);let active=true;db.current.auth.getSession().then(({data:{session}})=>{if(!active)return;setSignedIn(!!session);if(session)void refresh();else setLoading(false);});const {data:{subscription}}=db.current.auth.onAuthStateChange((event,session)=>{if(!active)return;setSignedIn(!!session);if(event==='SIGNED_IN')setTimeout(()=>{if(active)void refresh();},0);if(event==='SIGNED_OUT'){setAllowed(false);setRows([]);setEdit(null);}});return()=>{active=false;subscription.unsubscribe();};},[ready,refresh]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const change=(key:keyof Project,value:unknown)=>{setEdit(e=>e?{...e,[key]:value}:null);setDirty(true);};
 async function login(){setBusy(true);setMessage('');try{const {error}=await db.current!.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/admin'}});if(error)throw error;}catch{setMessage('로그인을 시작하지 못했습니다. 연결 설정을 확인해 주세요.');setBusy(false);}}
 async function save(p:ViewProject){setBusy(true);setMessage('');try{const clean=projectSchema.safeParse(p);if(!clean.success)throw new Error(clean.error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('\n'));const res=await request('/api/admin/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(clean.data)});const saved:ViewProject=await res.json();setRows(old=>[...old.filter(x=>x.id!==saved.id),saved].sort((a,b)=>a.sort_order-b.sort_order));if(edit?.id===saved.id)setEdit(saved);setDirty(false);setMessage('저장했습니다.');}catch(e){setMessage(e instanceof Error?e.message:'저장에 실패했습니다.');}finally{setBusy(false);}}
 async function upload(file:File|undefined,kind:'cover'|'screenshot'){if(!file||!edit)return;setBusy(true);setMessage('');try{const form=new FormData();form.set('file',file);const res=await request('/api/admin/upload',{method:'POST',body:form});const result=await res.json();setEdit(e=>!e?null:kind==='cover'?{...e,cover:result.path,coverSrc:result.src}:{...e,screenshots:[...e.screenshots,result.path],screenshotSrcs:[...e.screenshotSrcs,result.src]});setDirty(true);setMessage('이미지를 올렸습니다. 저장 버튼을 눌러 기록에 반영해 주세요.');}catch(e){setMessage(e instanceof Error?e.message:'업로드에 실패했습니다.');}finally{setBusy(false);}}
 function close(){if(dirty&&!confirm('저장하지 않은 변경을 버리고 목록으로 돌아갈까요?'))return;setEdit(null);setDirty(false);setPreview(false);setMessage('');}
 async function exportData(){setBusy(true);try{const res=await request('/api/admin/export');const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download='gayoung-projects.json';a.click();URL.revokeObjectURL(url);setMessage('프로젝트 정보를 내려받았습니다. 이미지 파일은 별도 백업 대상입니다.');}catch(e){setMessage(e instanceof Error?e.message:'내보내기 실패');}finally{setBusy(false);}}
 if(!ready)return <div className="admin-intro"><p className="eyebrow">GAYOUNG / ADMIN</p><h1>기록을 관리하는 곳.</h1><p>새 프로젝트를 올리고, 소개와 화면을 다듬는 가영님 전용 공간입니다.</p><div className="notice"><strong>관리자 연결을 준비하고 있습니다.</strong><p>연결이 완료되면 지정한 구글 계정으로 로그인할 수 있습니다.</p></div><a className="text-link" href="/">포트폴리오로 돌아가기 →</a></div>;
 return <><div className="admin-heading"><div><p className="eyebrow">GAYOUNG / ADMIN</p><h1>프로젝트 관리</h1><p className="muted">장사에서 시작한 기록을 하나씩 쌓아갑니다.</p></div>{signedIn&&<button className="secondary" onClick={async()=>{if(dirty&&!confirm('저장하지 않고 로그아웃할까요?'))return;await db.current?.auth.signOut();setDirty(false);}}>로그아웃</button>}</div><p className="message" role="status" aria-live="polite">{message}</p>{loading?<p>기록을 불러오고 있습니다.</p>:!signedIn?<div className="admin-intro"><h2>가영님, 안녕하세요.</h2><p>등록된 관리자 구글 계정으로 로그인해 주세요.</p><div className="toolbar"><button className="primary" disabled={busy} onClick={login}>구글 계정으로 로그인 ↗</button></div></div>:!allowed?<div className="notice"><p>관리자 권한 또는 데이터 연결을 확인할 수 없습니다.</p><button className="secondary" onClick={refresh}>다시 확인</button></div>:edit?<>
 <div className="toolbar"><button className="secondary" disabled={busy} onClick={close}>← 목록</button><button className="secondary" onClick={()=>setPreview(!preview)}>{preview?'입력으로 돌아가기':'현재 내용 미리보기'}</button></div>
 {preview?<section className="admin-preview"><p className="eyebrow">공개 전 미리보기 · {names[edit.visibility]}</p><h2>{edit.title||'프로젝트 이름'}</h2><p>{edit.summary}</p>{edit.coverSrc&&<Image src={edit.coverSrc} width={1200} height={720} alt="디자인 커버 미리보기"/>}{edit.screenshotSrcs.map((s,i)=><Image key={i} src={s} width={1364} height={940} alt="실제 화면 미리보기"/>)}<p>{edit.capture_note}</p>{[['만든 이유',edit.problem],['사용 방법',edit.steps],['제작 과정',edit.process],['구현 범위',edit.scope],['다음 개선',edit.next]].map(([label,text])=><div key={label}><h2>{label}</h2><p style={{whiteSpace:'pre-line'}}>{text}</p></div>)}</section>:<form id="project-form" onSubmit={e=>{e.preventDefault();void save(edit);}}><fieldset disabled={busy} style={{border:0,padding:0,margin:0}}><div className="form-grid">
 {(['title','summary','slug','url','category','status'] as const).map((key,i)=><label className={'field '+(key==='summary'?'full':'')} key={key}>{['프로젝트 이름 *','짧은 소개 *','상세 주소 이름 *','실제 사이트 주소 *','분야','구현 상태 안내'][i]}<input required={['title','summary','slug','url'].includes(key)} type={key==='url'?'url':'text'} value={edit[key]} maxLength={key==='summary'?300:key==='url'?2000:150} onChange={e=>change(key,e.target.value)} placeholder={key==='slug'?'예: new-project':key==='url'?'https://':''}/>{key==='slug'&&<small>영문 소문자·숫자·하이픈. 공개 후 변경하면 기존 공유 주소가 바뀝니다.</small>}</label>)}
 <label className="field">노출 순서<input type="number" min="0" max="100000" value={edit.sort_order} onChange={e=>change('sort_order',Number(e.target.value))}/><small>작은 숫자가 먼저 보입니다.</small></label><label className="field">공개 상태<select value={edit.visibility} onChange={e=>change('visibility',e.target.value)}>{Object.entries(names).filter(([k])=>k!=='trash').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <div className="field full"><span>디자인 썸네일</span>{edit.coverSrc&&<Image className="upload-preview" src={edit.coverSrc} width={1200} height={720} alt="현재 썸네일"/>}<label>커버 이미지 선택<input aria-label="커버 이미지 선택" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{void upload(e.target.files?.[0],'cover');e.target.value='';}}/></label><small>PNG·JPG·WebP / 3MB 이하. 첫 5개 프로젝트에는 디자인 커버가 등록되어 있습니다.</small></div>
 <div className="field full"><span>실제 사이트 화면 · 최대 12개</span>{edit.screenshotSrcs.map((src,i)=><div className="asset-row" key={i}><Image className="upload-preview" src={src} width={1364} height={940} alt={`실제 캡처 ${i+1}`}/><button type="button" className="secondary" onClick={()=>{setEdit({...edit,screenshots:edit.screenshots.filter((_,j)=>i!==j),screenshotSrcs:edit.screenshotSrcs.filter((_,j)=>i!==j)});setDirty(true);}}>이 캡처 빼기</button></div>)}<label>실제 캡처 추가<input aria-label="실제 캡처 추가" type="file" accept="image/png,image/jpeg,image/webp" disabled={edit.screenshots.length>=12} onChange={e=>{void upload(e.target.files?.[0],'screenshot');e.target.value='';}}/></label><small>첫 번째 캡처가 홈에 표시됩니다. 업로드 시점과 실제 캡처 시점은 다를 수 있으므로 확인 날짜는 직접 입력해 주세요.</small></div>
 <label className="field">캡처 안내<input value={edit.capture_note} onChange={e=>change('capture_note',e.target.value)}/></label><label className="field">캡처 확인 날짜<input type="date" value={edit.captured_at.slice(0,10)} onChange={e=>change('captured_at',e.target.value)}/></label>
 {(['problem','steps','process','scope','next'] as const).map((key,i)=><label className="field full" key={key}>{['왜 만들었나요?','이렇게 사용해요 · 한 줄에 한 단계','제작 과정과 본인 역할','지금 가능한 것 · 데모와 제한 포함','앞으로 개선할 점'][i]}<textarea value={edit[key]} maxLength={5000} onChange={e=>change(key,e.target.value)}/></label>)}
 </div></fieldset></form>}
 <div className="form-actions"><button className="primary" disabled={busy} onClick={()=>void save(edit)}>{busy?'저장 중…':names[edit.visibility]+' 상태로 저장'}</button><button className="secondary" disabled={busy} onClick={close}>목록으로</button>{dirty&&<span className="muted">아직 저장하지 않은 변경이 있습니다.</span>}</div>
 </>:<><div className="toolbar"><button className="primary" disabled={busy} onClick={()=>{setEdit(empty());setMessage('');}}>새 프로젝트 +</button><button className="secondary" disabled={busy} onClick={exportData}>정보 내보내기</button><label>보기 <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">전체 기록</option><option value="published">공개</option><option value="draft">임시저장</option><option value="hidden">비공개</option><option value="trash">휴지통</option></select></label></div><div className="admin-list">{rows.filter(p=>filter==='active'?p.visibility!=='trash':p.visibility===filter).map(p=><article className="admin-row" key={p.id}><div><h3>{p.title}</h3><p>{names[p.visibility]} · 순서 {p.sort_order} · /projects/{p.slug}</p></div><div className="toolbar">{p.visibility==='trash'?<button className="secondary" disabled={busy} onClick={()=>void save({...p,visibility:'draft'})}>임시저장으로 복구</button>:<><button className="secondary" disabled={busy} onClick={()=>{setEdit(p);setMessage('');}}>수정</button><button className="secondary danger" disabled={busy} onClick={()=>{if(confirm('휴지통으로 옮길까요? 공개 목록에서 숨겨지며 나중에 복구할 수 있습니다.'))void save({...p,visibility:'trash'});}}>휴지통</button></>}</div></article>)}{!rows.some(p=>filter==='active'?p.visibility!=='trash':p.visibility===filter)&&<p className="notice">이 상태의 프로젝트가 없습니다.</p>}</div></>}
 </>;
}
