/** Public editorial records; operational data and credentials never belong here. */
export const schoolLabel = '배민아카데미 AI 장사스쿨';
// Explicit attribution, not an automatic date comparison: the precise first class date is unconfirmed.
export const schoolSlugs = ['menu-finder','online-prepay','promo-studio','official-site','menu-play','order-call'];
export const presentationOrder = ['menu-finder','online-prepay','promo-studio','official-site','menu-play','order-call'];
export type WorkRecord = {
 slug:string; title:string; summary:string; category:string; status:string;
 period:string; label:string; cover:[string,string]; url?:string;
 problem:string; steps:string[]; process:string; current:string[];
 before:string; after:string; evidence:string; next:string[]; demo:string;
};
export const recentWorks:WorkRecord[] = [
 {slug:'promo-studio',title:'우리 가게 홍보 도우미',summary:'가게의 색과 분위기를 담아, 홍보물 제작 요청을 쉽게.',category:'홍보 · 프롬프트 제작',status:'공개 운영 · 개선 중',period:'2026. 10',label:'PROMO STUDIO',cover:['우리 가게답게,','홍보를 쉽게.'],url:'https://restaurant-promo-studio.vercel.app/',problem:'AI를 처음 쓰는 사장님은 음식 사진, 브랜드 색상, 게시할 곳을 어떻게 설명해야 할지 막막합니다. 같은 사진으로도 결과 스타일이 달라지는 문제를 줄이고 싶었습니다.',steps:['가게와 메뉴 정보 입력','브랜드 색상·분위기와 사용할 매체 선택','정리된 프롬프트 복사','ChatGPT에서 실제 음식 원본·로고를 첨부하고 제작'],process:'배민아카데미 AI 플레이북의 매체별 광고 소재 작업을 계기로, 반복하던 질문과 제작 기준을 웹 입력 흐름으로 정리했습니다. 포핸즈·태백산 등 음식점 사례로 문구와 이미지 결과를 검토하며 원본 사진, 색상, 분위기의 중요성을 확인했습니다.',current:['단계별 입력과 제작 프롬프트 생성·복사','네이버·인스타그램·카카오톡 등 사용처별 요청 정리','선택한 경우 같은 브라우저에 입력 정보 저장','카카오톡 내부 브라우저의 외부 열기 안내'],before:'새 작업마다 필요한 정보와 제작 조건을 대화에서 다시 설명했습니다.',after:'입력한 정보를 정해진 순서의 요청문으로 묶어 복사할 수 있습니다.',evidence:'코드·제작 사례 확인. 실제 사용 시간 절감은 미측정입니다.',next:['아이폰·갤럭시의 실제 카카오톡 환경 확인','다른 사장님의 입력·복사 흐름 피드백 반영','원본 사진을 사용한 매체별 결과 품질 점검'],demo:'가상 메뉴 정보를 입력한 뒤 프롬프트를 복사하는 장면을 보여줍니다. 사이트 자체가 이미지를 생성하거나 사진을 업로드받는 도구는 아닙니다.'},
 {slug:'official-site',title:'가영이네 공식 사이트',summary:'가게 이야기부터 메뉴와 선결제까지, 한곳에서.',category:'브랜드 · 매장 안내',status:'기획·제작 진행 중',period:'2026. 10',label:'GAYOUNGENE HOME',cover:['우리 가게의','온라인 입구.'],problem:'메뉴 안내와 선결제 주소가 나뉘어 있어 손님에게 각각 설명해야 했습니다. 가영이네의 이야기와 필요한 서비스를 함께 찾는 입구를 만들고 있습니다.',steps:['홈에서 가게 이야기 확인','다국어 메뉴 안내로 이동','필요할 때 선결제 신청으로 이동'],process:'gayoungene.com 도메인을 구매하고 홈·메뉴·선결제의 주소 구조를 정했습니다. 어머니 얼굴을 직접 그린 공식 로고, 수제 음식의 이야기, 오렌지와 캐릭터를 중심으로 브랜드 경험을 기획했습니다.',current:['홈 / 메뉴 / 선결제의 통합 구조 기획','공식 로고 원본 유지와 브랜드 이야기 정리','모바일 중심의 글자·버튼·동작 방향 설정'],before:'손님에게 서비스별 링크와 가게 정보를 따로 안내해야 했습니다.',after:'하나의 입구에서 필요한 서비스로 이동하는 구조를 설계했습니다.',evidence:'기획 기록 기준. 도메인 연결과 운영 배포 완료는 확인 전입니다.',next:['통합 화면과 실제 연결 상태 검수','기존 QR 주소 유지 확인','매장 사진과 브랜드 이야기 보강'],demo:'통합 구조와 브랜드 방향을 설명하는 기획 기록입니다. 운영 확인 전인 주소는 체험 링크로 노출하지 않습니다.'},
 {slug:'menu-play',title:'게임형 메뉴 추천',summary:'말랑 가영이와 몇 번 고르면, 먹고 싶은 메뉴에 도착.',category:'고객 경험 · 메뉴 추천',status:'기획·개발 준비',period:'2026. 10',label:'MENU PLAY',cover:['고르는 시간이','즐거워지도록.'],problem:'낯선 메뉴가 많으면 외국인 손님이 읽다가 포기할 수 있습니다. 기존 메뉴 안내에서 더 나아가, 선택에 캐릭터가 반응하는 짧고 쉬운 경험을 구상했습니다.',steps:['언어와 피하고 싶은 재료 확인','음식 취향과 허용 맵기 선택','대표 메뉴 1개와 대안 최대 2개 확인','매장 주문 위치 안내'],process:'손님이 실제로 쓰게 만들자는 피드백을 바탕으로 레트로 게임 분위기와 말랑 가영이·토끼의 반응을 기획했습니다. 기존 메뉴 안내와 별도의 확장 프로젝트로 준비하고 있습니다.',current:['30~45초 체험을 목표로 한 사용 흐름 기획','캐릭터 표정·동작과 다국어 화면 방향 정리','기존 메뉴 안내와 구분된 개발 준비'],before:'메뉴 목록과 설명을 읽으며 직접 선택해야 했습니다.',after:'짧은 질문과 캐릭터 반응으로 선택을 돕는 흐름을 설계했습니다.',evidence:'기획 단계입니다. 30~45초는 목표이며 측정 결과가 아닙니다.',next:['핵심 선택 흐름 구현','재료 미확인·빈 결과 안내 검토','외국인 손님 관점의 모바일 테스트'],demo:'선택 순서와 캐릭터 반응의 기획을 소개합니다. 완성된 게임이나 검증된 알레르기 추천으로 설명하지 않습니다.'},
 {slug:'order-call',title:'매장 주문 호출 화면',summary:'기다리는 손님에게, 준비 상황을 분명하게.',category:'매장 운영 · 픽업 안내',status:'설계·개발 진행 중',period:'2026. 10',label:'ORDER CALL',cover:['기다림에도,','안내가 필요해요.'],problem:'엄마와 둘이 조리하며 손님에게 대기 상황과 픽업을 반복해서 안내해야 합니다. 매장 태블릿에 준비 상황을 보여주는 방법을 설계했습니다.',steps:['직원이 주문번호 직접 입력','매장 혼잡도와 예상 대기시간 선택','음식 준비 후 번호 호출','완료 또는 취소 처리'],process:'매장 Galaxy Tab A8 사용 환경을 기준으로 고객용 대기 화면과 직원용 조작 흐름을 구상했습니다. 주문번호 자동 연동 대신 직원이 직접 번호를 입력하는 방식으로 범위를 정했습니다.',current:['보통·혼잡·매우 혼잡의 상태 설계','5·10·20·30분 대기시간 선택 기획','한국어·영어 호출과 완료·취소 흐름 설계'],before:'조리 중 대기시간을 말로 설명하고 준비된 주문을 직접 불렀습니다.',after:'직원이 입력한 번호와 대기 안내를 화면에 보여주는 흐름을 설계했습니다.',evidence:'운영 요구사항 기준. 현장 동작과 음성 호출 검증은 확인 전입니다.',next:['태블릿 화면과 실제 호출 동작 확인','직원 조작 횟수와 오입력 복구 점검','손님이 대기 상태를 이해하는지 현장 검수'],demo:'고객 화면과 직원의 조작 흐름을 설명합니다. 페이히어 주문번호가 자동으로 들어오는 기능은 포함하지 않습니다.'}
];
export type ProjectUpdate={status:string;url:string;summary:string;current:string[];before:string;after:string;evidence:string;next:string[];demo:string};
export const updates:Record<string,ProjectUpdate>={
 'menu-finder':{status:'7개 언어 공개 · 개선 중',url:'https://gayoungene-menu-finder.vercel.app/',summary:'샘플 메뉴 8개에서 실제 메뉴 32개를 안내하는 사이트로 발전했습니다.',current:['영어·일본어·중국어·베트남어·몽골어·인도네시아어·프랑스어 안내','실제 메뉴 32개, 원본 사진 18장과 사진 준비 중 표시','나라별 추천·맵기·재료 취향 검색·직원에게 보여주기','시트 정보를 검토해 수동 반영하는 방식'],before:'낯선 메뉴의 이름·재료·맵기를 손님에게 반복해서 설명해야 했습니다.',after:'손님이 사진과 다국어 설명을 보고 메뉴를 좁힌 뒤 한국어 화면을 직원에게 보여줄 수 있습니다.',evidence:'최신 저장소와 가상 사용자 브라우저 점검 기록 기준. 실제 고객의 선택 시간·설명 시간은 미측정입니다.',next:['실제 손님 사용 기록','원어민 번역 검수와 누락 사진 보완','원재료 확인과 취향 검색 안내 개선'],demo:'언어 선택 → 나라별 추천 또는 맵기 선택 → 메뉴 상세 → 직원에게 보여주기. 주문·결제는 매장 기기에서 진행하며 재료 검색은 알레르기 안전을 보증하지 않습니다.'},
 'online-prepay':{status:'매장 QR 신청·알림 활용 중',url:'https://gayoungene-prepay.vercel.app/',summary:'종이 장부와 계산기를 쓰던 선결제 업무를, 고객의 QR 신청과 사장님의 텔레그램 알림 확인으로 바꿨습니다.',current:['AI로 만든 신청 QR 포스터를 매장에서 활용','온라인 신청서 작성 후 별도의 제로페이 QR로 결제','신청 시 텔레그램으로 연락처·금액·적립 내역 알림 수신','계산된 총 충전 금액을 보고 페이히어에서 직접 충전','신청 내역을 디지털 장부에 저장'],before:'고객이 종이 장부에 정보를 적으면 결제를 도와드리고, 페이히어에서 고객을 찾은 뒤 계산기로 적립금을 계산해 직접 충전했습니다.',after:'고객은 QR로 신청하고 결제합니다. 저는 텔레그램에 온 연락처와 계산된 금액을 보고 페이히어에서 직접 충전합니다.',evidence:'매장 활용 과정은 운영자의 설명 기준입니다. 계산기를 사용하는 단계가 줄었으며, 정확한 처리 시간은 아직 측정하지 않았습니다.',next:['네이버 공지·블로그에 비대면 선결제 신청 안내 게시','실제 고객의 신청·처리 시간 기록','쌓인 신청 데이터를 활용한 관리·통계 검토'],demo:'매장 QR 포스터 → 온라인 신청 화면 → 별도 결제 → 텔레그램 신청 알림 → 페이히어 직접 충전 순서를 보여줍니다. 신청 알림은 결제 완료 알림과 다르며, 실제 결제 확인은 별도로 필요합니다.'}
};
